export const CREATE_FORM_REQUEST = "CREATE_FORM_REQUEST"
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS"
export const CREATE_FORM_FAIL = "CREATE_FORM_FAIL"

export const STUDENT_FORM_REQUEST = "STUDENT_FORM_REQUEST"
export const STUDENT_FORM_SUCCESS = "STUDENT_FORM_SUCCESS"
export const STUDENT_FORM_FAIL = "STUDENT_FORM_FAIL"

export const TEACHER_FORM_REQUEST = "TEACHER_FORM_REQUEST"
export const TEACHER_FORM_SUCCESS = "TEACHER_FORM_SUCCESS"
export const TEACHER_FORM_FAIL = "TEACHER_FORM_FAIL"

export const FORM_DETAILS_REQUEST = "FORM_DETAILS_REQUEST"
export const FORM_DETAILS_SUCCESS = "FORM_DETAILS_SUCCESS"
export const FORM_DETAILS_FAIL = "FORM_DETAILS_FAIL"

export const FORM_DELETE_REQUEST = "FORM_DELETE_REQUEST"
export const FORM_DELETE_SUCCESS = "FORM_DELETE_SUCCESS"
export const FORM_DELETE_RESET = "FORM_DELETE_RESET"
export const FORM_DELETE_FAIL = "FORM_DELETE_FAIL"

export const TEACHER_FORM_UPDATE_REQUEST = "TEACHER_FORM_UPDATE_REQUEST"
export const TEACHER_FORM_UPDATE_SUCCESS = "TEACHER_FORM_UPDATE_SUCCESS"
export const TEACHER_FORM_UPDATE_FAIL = "TEACHER_FORM_UPDATE_FAIL"
export const TEACHER_FORM_UPDATE_RESET = "TEACHER_FORM_UPDATE_RESET"


export const CLEAR_ERRORS = "CLEAR_ERRORS";