export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_TEACHER_REQUEST = "REGISTER_TEACHER_REQUEST";
export const REGISTER_TEACHER_SUCCESS = "REGISTER_TEACHER_SUCCESS";
export const REGISTER_TEACHER_FAIL = "REGISTER_TEACHER_FAIL";

export const LOAD_TEACHER_REQUEST = "LOAD_TEACHER_REQUEST";
export const LOAD_TEACHER_SUCCESS = "LOAD_TEACHER_SUCCESS";
export const LOAD_TEACHER_FAIL = "LOAD_TEACHER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_TEACHERS_REQUEST = "ALL_TEACHERS_REQUEST";
export const ALL_TEACHERS_SUCCESS = "ALL_TEACHERS_SUCCESS";
export const ALL_TEACHERS_FAIL = "ALL_TEACHERS_FAIL";

export const ALL_OWNERS_REQUEST = "ALL_OWNERS_REQUEST";
export const ALL_OWNERS_SUCCESS = "ALL_OWNERS_SUCCESS";
export const ALL_OWNERS_FAIL = "ALL_OWNERS_FAIL";

export const TEACHER_DETAILS_REQUEST = "TEACHER_DETAILS_REQUEST";
export const TEACHER_DETAILS_SUCCESS = "TEACHER_DETAILS_SUCCESS";
export const TEACHER_DETAILS_FAIL = "TEACHER_DETAILS_FAIL";

export const UPDATE_TEACHER_REQUEST = "UPDATE_TEACHER_REQUEST";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_RESET = "UPDATE_TEACHER_RESET";
export const UPDATE_TEACHER_FAIL = "UPDATE_TEACHER_FAIL";

export const DELETE_TEACHER_REQUEST = "DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAIL = "DELETE_TEACHER_FAIL";
export const DELETE_TEACHER_RESET = "DELETE_TEACHER_RESET";

export const DELETE_OWNER_REQUEST = "DELETE_OWNER_REQUEST";
export const DELETE_OWNER_SUCCESS = "DELETE_OWNER_SUCCESS";
export const DELETE_OWNER_FAIL = "DELETE_OWNER_FAIL";
export const DELETE_OWNER_RESET = "DELETE_OWNER_RESET";

export const WARN_STUDENT_REQUEST = "WARN_STUDENT_REQUEST";
export const WARN_STUDENT_SUCCESS = "WARN_STUDENT_SUCCESS";
export const WARN_STUDENT_FAIL = "WARN_STUDENT_FAIL";
export const WARN_STUDENT_RESET = "WARN_STUDENT_RESET";

export const INCREASE_REWARDS_REQUEST = "INCREASE_REWARDS_REQUEST"
export const INCREASE_REWARDS_SUCCESS = "INCREASE_REWARDS_SUCCESS"
export const INCREASE_REWARDS_FAIL = "INCREASE_REWARDS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";