export const TEACHER_TRANSACTION_REQUEST = "TEACHER_TRANSACTION_REQUEST"
export const TEACHER_TRANSACTION_SUCCESS = "TEACHER_TRANSACTION_SUCCESS"
export const TEACHER_TRANSACTION_FAIL = "TEACHER_TRANSACTION_FAIL"

export const STUDENT_TRANSACTION_REQUEST = "STUDENT_TRANSACTION_REQUEST"
export const STUDENT_TRANSACTION_SUCCESS = "STUDENT_TRANSACTION_SUCCESS"
export const STUDENT_TRANSACTION_FAIL = "STUDENT_TRANSACTION_FAIL"

export const REWARD_TRANSACTION_REQUEST = "REWARD_TRANSACTION_REQUEST"
export const REWARD_TRANSACTION_SUCCESS = "REWARD_TRANSACTION_SUCCESS"
export const REWARD_TRANSACTION_FAIL = "REWARD_TRANSACTION_FAIL"

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST"
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS"
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"